######################################################################
# Automatically generated by qmake (3.0) ?? 12? 2 22:12:00 2017
######################################################################

TEMPLATE = app
TARGET = external
INCLUDEPATH += .

# Input
SOURCES += external.c


